### ISSUE TITLE
[FEATURE] Enable to use alternative database authentication in the DocumentDB JDBC driver.

### ISSUE THREAD

**Issue by affonsov** [aws/amazon-documentdb-jdbc-driver#279]
## Is your feature request related to a problem? Please describe.

Yes. Not being able to connect to mongoDB instance.

## Describe the solution you'd like

Currently it is not possible to authenticate in a mongo instance due DocumentDB JDBC driver not expose the auth database.

**Comment by Rainson12** [comment]
If you use Mongodb you should be able to use the BI connector from mongodb: https://www.mongodb.com/try/download/bi-connector
