### ISSUE TITLE
[FEATURE] Implement JDBC `.getTypeInfo()`

### ISSUE THREAD

**Issue by GavinRay97** [aws/amazon-documentdb-jdbc-driver#354]
This is useful because tools like [SchemaCrawler](https://github.com/schemacrawler/SchemaCrawler) provide a uniform interface for getting schema information from JDBC datasources, but one of the requirements is a minimal implementation of `getTypeInfo()`

If this isn't too huge of a lift, maybe I can attempt a PR here if someone could give some hints on what the implementation should be?

```kt
@Test
fun `test SchemaCrawler`() {
    val dataSource = DocumentDbDataSource().apply {
        hostname = "localhost:27017"
        database = "sample"
        user = "root"
    }

    val options = SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
   // Create a default TypeMap
    val retrievalOptions = SchemaRetrievalOptionsBuilder.builder()
        .withTypeMap(TypeMap())
        .toOptions()

    val catalog = SchemaCrawlerUtility.getCatalog(dataSource.connection, retrievalOptions,
        options, schemacrawler.tools.options.Config())

    println(catalog.tables)
}
```
```java
Caused by: java.sql.SQLFeatureNotSupportedException
	at software.amazon.documentdb.jdbc.DocumentDbDatabaseMetaData.getTypeInfo(DocumentDbDatabaseMetaData.java:650)
	at schemacrawler.crawl.DataTypeRetriever.retrieveSystemColumnDataTypesFromMetadata(DataTypeRetriever.java:179)
	at schemacrawler.crawl.DataTypeRetriever.retrieveSystemColumnDataTypes(DataTypeRetriever.java:84)
	at schemacrawler.crawl.RetrievalStopWatch.lambda$time$0(RetrievalStopWatch.java:105)
	at us.fatehi.utility.StopWatch.time(StopWatch.java:142)
	at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:100)
	at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:72)
	at schemacrawler.crawl.SchemaCrawler.crawlColumnDataTypes(SchemaCrawler.java:201)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:143)
```

**Comment by andiemontoyeah** [comment]
Hi @GavinRay97, 
Thank you for your interest in our driver and for taking the time to submit an issue! 

We think this enhancement should be fairly straightforward if you are interested in taking it on. 

The implementation for `GetTypeInfo()` (which is currently throwing an exception) is [here](https://github.com/aws/amazon-documentdb-jdbc-driver/blob/6524d3ab2e82b7d56b9d01b8b51f4976080f62dc/src/main/java/software/amazon/documentdb/jdbc/DocumentDbDatabaseMetaData.java#L642). 
The other supported DatabaseMetaDataResultSets are implemented [here](https://github.com/aws/amazon-documentdb-jdbc-driver/blob/develop/src/main/java/software/amazon/documentdb/jdbc/DocumentDbDatabaseMetaDataResultSets.java) and are a good reference. Our list of supported data types is [here](https://github.com/aws/amazon-documentdb-jdbc-driver/blob/develop/src/markdown/sql/sql-limitations.md#data-types). They are a subset of the supported data types in this [list](https://calcite.apache.org/docs/reference.html#scalar-types) which has more details.

We have allocated capacity in our current iteration to support your work on this or to take it on as well if time permits. 
Let us know if you have any questions on this issue or anything else.
Thanks, Andie

**Comment by GavinRay97** [comment]
Okay, I've managed to get enough of this implemented that it passes the `getTypeInfo()` point! Thanks for your help =)

Now the next issue is that it finds the `sample` collection I have, but no tables inside of the collection:
```java
Jun 15, 2022 3:33:43 PM schemacrawler.crawl.SchemaCrawler crawl
INFO: 
-- generated by: SchemaCrawler 16.16.14
-- generated on: 2022-06-15T19:33:43.4393993
-- database: DocumentDB 4.0
-- driver: DocumentDB JDBC Driver 1.2.4-beta.1
-- operating system: Windows 10 10.0
-- JVM system: Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.1+12


Jun 15, 2022 3:33:43 PM schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
INFO: Processed 0 catalogs
Jun 15, 2022 3:33:43 PM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
INFO: Processed 1 schemas

...

Jun 15, 2022 3:33:43 PM schemacrawler.crawl.DataTypeRetriever retrieveSystemColumnDataTypesFromMetadata
INFO: Processed 3 system column data types

...

Jun 15, 2022 3:33:43 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Jun 15, 2022 3:33:43 PM schemacrawler.crawl.TableRetriever retrieveTablesFromMetadata
INFO: Retrieving tables for schema <sample>
Jun 15, 2022 3:33:43 PM schemacrawler.crawl.TableRetriever retrieveTablesFromMetadata
INFO: Processed 0 tables
Jun 15, 2022 3:33:43 PM schemacrawler.crawl.SchemaCrawler crawlTables
INFO: Retrieved 0 tables

...

INFO: Total time taken for <standard> - 00:00:00.025 hours
-  0.0% - 00:00:00.000 - <retrieveAdditionalDatabaseInfo>
-  0.0% - 00:00:00.000 - <retrieveServerInfo>
-  0.0% - 00:00:00.000 - <retrieveDatabaseUsers>
-  0.0% - 00:00:00.000 - <retrieveAdditionalJdbcDriverInfo>
- 44.0% - 00:00:00.011 - <retrieveSchemas>
-  0.0% - 00:00:00.000 - <filterAndSortSchemas>
- 36.0% - 00:00:00.009 - <retrieveColumnDataTypes>
-  0.0% - 00:00:00.000 - <retrieveUserDefinedColumnDataTypes>
-  8.0% - 00:00:00.002 - <retrieveTables>
```

So I will continue to debug this, and contribute a PR with my implementation once it all works
(If I can't get it working, I'll finish the TypeInfo stuff and PR it anyways)

---

EDIT: It is because the below returns no rows:
```java
// catalogName = null
// schemaName = "sample"
// tableNamePattern = null
// filteredTableTypes = ["table"]
DatabaseMetaData
    .getMetaData()
    .getTables(catalogName, schemaName, tableNamePattern, filteredTableTypes.toArray()), "DatabaseMetaData::getTables"))
```

![image](https://user-images.githubusercontent.com/26604994/173911820-5daa395e-57c7-4dc6-ae5f-534882a90c88.png)

**Comment by GavinRay97** [comment]
With changes to `getColumns()` + `getTables()` to account for `null` name pattern being equivalent to "give me everything", ta-da! 🥳 

(It has a weird type for `DOUBLE` because I only added `VARCHAR` and `BOOLEAN` types in `getTypeInfo()` for testing, I think)

![image](https://user-images.githubusercontent.com/26604994/173918392-ebb2d7a0-f1c3-424d-8520-4aa700ad765d.png)

**Comment by andiemontoyeah** [comment]
Hi @GavinRay97, 

This is great news!! Really exciting as well to see it working with SchemaCrawler. We will take a look at your PR in the coming days. 

We were not aware that `null` for the `tableNamePattern` should behave the same as "%" based on the Oracle documentation. Can you confirm this is also the behaviour on other databases that you have used with SchemaCrawler?

Our Github actions are not yet setup for external contributions and rely on repository secrets. The PR build will not be able to run but we should still be able to review it.

If you haven't already, to test your change locally and run any tests / formatting checks, and make sure any unit tests are updated, you can disable remote tests while you are developing: https://github.com/aws/amazon-documentdb-jdbc-driver/blob/6524d3ab2e82b7d56b9d01b8b51f4976080f62dc/gradle.properties#L11 

Thank you so much!!

**Comment by andiemontoyeah** [comment]
Feature and bug fix were released as part of https://github.com/aws/amazon-documentdb-jdbc-driver/releases/tag/v1.3.0. Thanks again for your contribution @GavinRay97!
