### ISSUE TITLE
Switch to Jsch-Fork

### ISSUE THREAD

**Issue by mwiede** [aws/amazon-documentdb-jdbc-driver#407]
## Is your feature request related to a problem? Please describe.

you might want to switch to https://github.com/mwiede/jsch

It's maintained and features more secure algorithms.

## Describe the solution you'd like

replace dependency com.jcraft:jsch with com.github.mwiede:jsch

**Comment by birschick-bq** [comment]
@mwiede 

Thanks for the heads-up, Matthais. I had not realized that the jcraft project had gone stale.

I will investigate switching to your fork and let you know if I run into any issues.

cc: @alexey-temnikov, @affonsoBQ

**Comment by birschick-bq** [comment]
Switch complete in #453
